CREATE TABLE PARTNER_CIM
	(
	CIM_ID int NOT NULL IDENTITY (1, 1),
	PARTNER_ID int NOT NULL,
	CIM_TIPUS int NULL,
	IRSZ varchar(4) NULL,
	VAROS varchar(50) NULL,
	CIM varchar(150) NULL
	)  ON [PRIMARY]
GO

ALTER TABLE PARTNER_CIM ADD CONSTRAINT
	PK_PARTNER_CIM PRIMARY KEY CLUSTERED 
	(
	CIM_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

CREATE TABLE PARTNER_TEL
	(
	TEL_ID int NOT NULL IDENTITY (1, 1),
	PARTNER_ID int NULL,
	TEL_TIPUS int NULL,
	TELEFON varchar(30) NULL
	)  ON [PRIMARY]
GO
ALTER TABLE PARTNER_TEL ADD CONSTRAINT
	PK_PARTNER_TEL PRIMARY KEY CLUSTERED 
	(
	TEL_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

CREATE TABLE PARTNER_VEVO
	(
	PARTNER_ID int NOT NULL,
	PARTNER_KOD varchar(20) NULL,
	NEM varchar(1) NULL,
	SZEMELYI_IG varchar(12) NULL,
	SZULETESNAP datetime NULL,
	NEVNAP_HO int NULL,
	NEVNAP_NAP int NULL,
	HITEL_CREDIT float(53) NULL
	)  ON [PRIMARY]
GO
ALTER TABLE PARTNER_VEVO ADD CONSTRAINT
	PK_PARTNER_VEVO PRIMARY KEY CLUSTERED 
	(
	PARTNER_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


GO
CREATE TABLE PARTNER_SZALL
	(
	PARTNER_ID nchar(10) NOT NULL,
	FIZETESI_MOD varchar(5) NULL,
	ATUTALAS_NAPOK int NULL,
	ADOSZAM varchar(14) NULL,
	KONTAKT_SZEMELY varchar(50) NULL,
	KONTAKT_ELERHET varchar(150) NULL
	)  ON [PRIMARY]
GO
ALTER TABLE PARTNER_SZALL ADD CONSTRAINT
	PK_PARTNER_SZALL PRIMARY KEY CLUSTERED 
	(
	PARTNER_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
CREATE TABLE PARTNER
	(
	PARTNER_ID int NOT NULL IDENTITY (1, 1),
	P_TIPUS varchar(1) NULL,
	P_NEV varchar(150) NULL,
	P_NEV2 varchar(150) NULL,
	P_NEV3 varchar(150) NULL
	)  ON [PRIMARY]
GO
ALTER TABLE PARTNER ADD CONSTRAINT
	PK_PARTNER PRIMARY KEY CLUSTERED 
	(
	PARTNER_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
CREATE TABLE dbo.PARTNER_BSZ
	(
	BSZ_ID int NOT NULL IDENTITY (1, 1),
	PARTNER_ID int NULL,
	BANK varchar(50) NULL,
	BANKSZAMLA varchar(24) NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.PARTNER_BSZ ADD CONSTRAINT
	PK_PARTNER_BSZ PRIMARY KEY CLUSTERED 
	(
	BSZ_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO


