CREATE TABLE BIZSZAM
	(
	CODE varchar(20) NOT NULL,
	COUNTER int NOT NULL
	)  ON [PRIMARY]
GO

ALTER TABLE BIZSZAM ADD CONSTRAINT
	DF_BIZSZAM_COUNTER DEFAULT 0 FOR COUNTER
GO

insert into BIZSZAM VALUES ('BEV',0)

GO

