CREATE TABLE PARTNER_TARTOZASOK
	(
	PARTNER_ID int NOT NULL,
	SOR_ID int NOT NULL IDENTITY (1, 1),
	JOGCIM varchar(50) NULL,
	MEGJEGYZES varchar(500) NULL,
	OSSZEG float(53) NULL,
	FIZETVE float(53) null
	)  ON [PRIMARY]
GO

ALTER TABLE PARTNER_TARTOZASOK ADD CONSTRAINT
	PK_PARTNER_TARTOZASOK PRIMARY KEY CLUSTERED 
	(
	PARTNER_ID,
	SOR_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO


CREATE TABLE PARTNER_BEFIZETESEK
	(
	PARTNER_ID int NOT NULL,
	SOR_ID int NOT NULL IDENTITY (1, 1),
	JOGCIM varchar(50) NULL,
	MEGJEGYZES varchar(500) NULL,
	OSSZEG float(53) NULL,
	KIPONTOZVA float(53) null
	)  ON [PRIMARY]
GO

ALTER TABLE PARTNER_BEFIZETESEK ADD CONSTRAINT
	PARTNER_BEFIZETESEK PRIMARY KEY CLUSTERED 
	(
	PARTNER_ID,
	SOR_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO


UPDATE VERSION  SET DB_VER = '034'

GO





