ALTER TABLE CIKK ADD
	CIKK_ROVID_NEV varchar(15) NULL,
	CIKK_TOP_LIST int NULL,
	CIKKCSOP_PREFER int NULL
GO
ALTER TABLE CIKK ADD CONSTRAINT
	DF_CIKK_CIKK_TOP_LIST DEFAULT 0 FOR CIKK_TOP_LIST
GO
ALTER TABLE CIKK ADD CONSTRAINT
	DF_CIKK_CIKKCSOP_PREFER DEFAULT 0 FOR CIKKCSOP_PREFER
GO

update CIKK set CIKK_ROVID_NEV = left(MEGNEVEZES,15), CIKK_TOP_LIST = 0, CIKKCSOP_PREFER = 0



GO

UPDATE VERSION  SET DB_VER = '022'

GO





