update CIKK set ELADASI_AR_NETTO = ELADASI_AR
GO
update CIKK set ELADASI_AR = ELADASI_AR_NETTO * (1 + (dbo.fn_get_afaszaz(CIKK_ID)/100))
GO
CREATE NONCLUSTERED INDEX IX_CIKCSOP_OTHER_FILTER ON dbo.CIKCSOP_OTHER_FILTER
	(
	CIKKCSOPORT_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX IX_CIKK ON dbo.CIKK
	(
	CIKKCSOPORT_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX IX_CIKK_1 ON dbo.CIKK
	(
	OTHER_FILTER_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


UPDATE VERSION  SET DB_VER = '018'

GO





