
CREATE TABLE CIKK_ARAK
	(
	CIKK_ID int NULL,
	ERVENYES_TOL datetime NULL,
	ERVENYES_IG datetime NULL,
	ELADASI_AR_N float(53) NULL
	)  ON [PRIMARY]
GO		

ALTER TABLE CIKK ADD
	SPEC_ZARAS int NULL
GO
ALTER TABLE CIKK ADD CONSTRAINT
	DF_CIKK_SPEC_ZARAS DEFAULT 0 FOR SPEC_ZARAS		
	
GO

ALTER TABLE CIKK ADD
	RECEPT_MODSZER varchar(100) NULL,
	RECEPT_ALK_TART varchar(100) NULL,
	RECEPT_POHAR varchar(100) NULL
GO

UPDATE VERSION  SET DB_VER = '010'

GO





