CREATE TABLE VERSION
	(
	DB_VER varchar(20) NOT NULL
	)  ON [PRIMARY]

GO

ALTER TABLE dbo.CIKK ADD
	SZJ_SZAM varchar(30) NULL,
	CIKKSZAM varchar(50) NULL,
	EAN_KOD varchar(28) NULL,
	MINIMUM_KESZLET float(53) NULL,
	OPTIMALIS_KESZLET float(53) NULL,
	ELADASI_AR float(53) NULL,
	HELYETTES_TERMEK int NULL,
	MAX_KEDVEZMENY_SZ float(53) NULL,
	MAX_KEDVEZM_FT float(53) NULL,
	MEGJEGYZES varchar(4000) null


GO

CREATE TABLE dbo.CIKK_BESZALLITOK
	(
	CIKK_ID int NULL,
	PARTNER_ID int NULL,
	BESZ_AR float(53) NULL
	)  ON [PRIMARY]

GO

