
DROP TABLE CIKK_ARAK
GO

CREATE TABLE  CIKK_ARAK (
	CIKK_ARAK_ID int NOT NULL,
	CIKK_ID int NULL,
	ERVENYES_TOL datetime NULL,
	ERVENYES_IG datetime NULL,
	ELADASI_AR_N float NULL,
 CONSTRAINT PK_CIKK_ARAK PRIMARY KEY CLUSTERED 
(
	CIKK_ARAK_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON PRIMARY
) ON PRIMARY

GO
ALTER TABLE CIKK_ARAK  WITH CHECK ADD  CONSTRAINT FK_CIKK_ARAK_CIKK FOREIGN KEY(CIKK_ID)
REFERENCES CIKK (CIKK_ID)
GO
ALTER TABLE CIKK_ARAK CHECK CONSTRAINT FK_CIKK_ARAK_CIKK

GO

CREATE TABLE CIKK_ARAK_DETAILS
	(
	CIKK_ARAK_ID int NOT NULL,
	LIT_KISZ_ID int NOT NULL,
	AR float(53) NULL
	)  ON PRIMARY
GO
ALTER TABLE CIKK_ARAK_DETAILS ADD CONSTRAINT
	PK_CIKK_ARAK_DETAILS PRIMARY KEY CLUSTERED 
	(
	CIKK_ARAK_ID,
	LIT_KISZ_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON PRIMARY

GO
ALTER TABLE dbo.CIKKCSOPORT ADD
	NEM_ELADO int NULL
GO
ALTER TABLE dbo.CIKKCSOPORT ADD CONSTRAINT
	DF_CIKKCSOPORT_NEM_ELADO DEFAULT 0 FOR NEM_ELADO
	
GO

	
UPDATE VERSION  SET DB_VER = '029'

GO





