
DROP TABLE _UZENETEK

GO

CREATE TABLE [_UZENETEK](
	[MIKOR] [datetime] NULL,
	[FELADO] [int] NULL,
	[SZOVEG] [varchar](8000) NULL,
	[OLVASVA] [int] NOT NULL CONSTRAINT [DF__UZENETEK_OLVASVA]  DEFAULT ((0)),
	[POS_X] [int] NULL,
	[POS_Y] [int] NULL,
	[UZENET_ID] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK__UZENETEK] PRIMARY KEY CLUSTERED 
(
	[UZENET_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


UPDATE VERSION  SET DB_VER = '014'

GO





