
insert into mozgas select 'EK','Eladás során történõ egyéb kivezetés',-1,null
GO
CREATE TABLE _SORSZAM
	(
	TYPE varchar(50) NOT NULL,
	COUNTER int NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE _SORSZAM ADD CONSTRAINT
	PK__SORSZAM PRIMARY KEY CLUSTERED 
	(
	TYPE
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO


UPDATE VERSION  SET DB_VER = '008'

GO





