CREATE TABLE LELTAR_FEJ(
	LELTAR_FEJ_ID int IDENTITY(1,1) NOT NULL,
	DATUM datetime NULL,
	RAKTAR_ID int NULL,
	CIKKCSOPORT_ID int NULL,
	LEZART int NULL CONSTRAINT DF_LELTAR_FEJ_LEZART  DEFAULT ((0)),
 CONSTRAINT PK_LELTAR_FEJ PRIMARY KEY CLUSTERED 
(
	LELTAR_FEJ_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON PRIMARY
) ON PRIMARY


GO
CREATE TABLE LELTAR_SOR
	(
	LELTAR_SOR_ID int NOT NULL IDENTITY (1, 1),
	LELTAR_FEJ_ID int NULL,
	CIKK_ID int NULL,
	AKT_KESZLET_MENNY float(53) NULL,
	SZAMOLT_MENNYISEG1 float(53) NULL,
	SZAMOLT_MENNYISEG2 float(53) NULL
	)  ON [PRIMARY]
GO
ALTER TABLE LELTAR_SOR ADD CONSTRAINT
	PK_LELTAR_SOR PRIMARY KEY CLUSTERED 
	(
	LELTAR_SOR_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

ALTER TABLE LELTAR_FEJ ADD
	STATUS int NULL
GO
ALTER TABLE LELTAR_FEJ ADD CONSTRAINT
	DF_LELTAR_FEJ_STATUS DEFAULT 1 FOR STATUS
	
GO
INSERT INTO  SYSPAR
           (PARAM_NAME, PARAM_VALUE_S, PARAM_VALUE_I, PARAM_VALUE_F, PARAM_VALUE_IMAGE)
     VALUES
           ('LELTAR_KOROK_SZAMA', '', 1, null,null)
           
GO

CREATE TABLE MEGRENDELES_FEJ
	(
	MEGRENDELES_FEJ_ID int NOT NULL IDENTITY (1, 1),
	DATUM datetime NULL,
	SZALLITO_ID int NULL,
	SORSZAM varchar(50) NULL,
	LEZART int NULL
	)  ON [PRIMARY]
GO
ALTER TABLE MEGRENDELES_FEJ ADD CONSTRAINT
	PK_MEGRENDELES_FEJ PRIMARY KEY CLUSTERED 
	(
	MEGRENDELES_FEJ_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

CREATE TABLE MEGRENDELES_SOR
	(
	SOR_ID int NOT NULL IDENTITY (1, 1),
	FEJ_ID int NULL,
	CIKK_ID int NULL,
	BESZ_AR float(53) NULL,
	MENNYISEG float(53) NULL
	)  ON [PRIMARY]
GO
ALTER TABLE MEGRENDELES_SOR ADD CONSTRAINT
	PK_MEGRENDELES_SOR PRIMARY KEY CLUSTERED 
	(
	SOR_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
	
UPDATE VERSION  SET DB_VER = '028'

GO





